<a href="https://colab.research.google.com/github/AnmolHemani/Advanced-Python/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/content/IMDB Dataset.csv")

In [3]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df['review']=df['review'].str.lower()

In [5]:
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [9]:
# Remove HTML tags

In [6]:
import re
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'',text)

In [7]:
text = "<html><body><p> Movie1 </p><p> Click here to <a href = 'https://google.com'>download</a></p>"

In [8]:
remove_html_tags(text)

' Movie1  Click here to download'

In [10]:
# now we remove tags from IMDB Datasets

In [11]:
df['review'] = df['review'].apply(remove_html_tags)

In [12]:
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [13]:
# if we want to remove urls from text then

In [14]:
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)

In [15]:
text1 = 'For notebook click here www.deture.com/delta/note1234acc'

In [16]:
remove_url(text1)

'For notebook click here '

In [17]:
# remove punctuation


In [19]:
import string
import time

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [20]:
exclude = string.punctuation

In [21]:
def remove_punc(text):
  for char in exclude:
    text = text.replace(char, '')
  return text

In [22]:
text1 = 'string. with . Punctuation'

In [23]:
remove_punc(text1)

'string with  Punctuation'

In [24]:
# spelling correction

In [25]:
!pip install TextBlob

In [26]:
from textblob import TextBlob

In [29]:
incorrect_text = "ceertain conditionas seveal genratuons aree modifed ih the samee maner,"
textblb = TextBlob(incorrect_text)
textblb.correct().string

'certain conditions several generations are modified in the same manner,'

In [30]:
# remove stopwords

In [31]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [32]:
STOPWORDS = set(stopwords.words('english'))

In [33]:
STOPWORDS

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [35]:
def remove_stopwords(text):
  new_text = []
  for word in text.split():
    if word in STOPWORDS:
      new_text.append('')
    else:
      new_text.append(word)
  x = new_text[:]
  new_text.clear()
  return "".join(x)

remove_stopwords('probably my all-time favourite movie , a story of selflessness , sacrifice , and dedicated to a noble cause.')

'probablyall-timefavouritemovie,storyselflessness,sacrifice,dedicatednoblecause.'

In [36]:
# Tokenization

In [40]:
# Word Tokenization
sent1 = "I am going to Delhi"
sent1.split()

['I', 'am', 'going', 'to', 'Delhi']

In [39]:
# Sentence Tokenization
sent2 = "I am going to Delhi. I will stay there for 3 days. Let\'s hope the trip to be great"
sent2.split('.')

['I am going to Delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [41]:
# NLTK

In [42]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [43]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [44]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [45]:
sent1 = "I am going to visit delhi!"
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [46]:
# Text Representation

In [47]:
# 1. Bag of words
# we use countvectorization

In [48]:
import numpy as np
import pandas as pd

In [49]:
df = pd.DataFrame({'text':['people watch cricket' , 'player was player' , 'people write comment' ,
                           'cricket play comment' ] , 'output':[1,1,0,0]})

In [50]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [51]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [52]:
bow = cv.fit_transform(df['text'])

In [53]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}


In [54]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [55]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

In [56]:
# 2. N-Grams

In [57]:
v = CountVectorizer(ngram_range=(1,2))

In [58]:
bow = v.fit_transform(df['text'])

In [59]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [60]:
#vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}


In [61]:
# TF (Term Frequency)
# IDF (Inverse Document Frequency)

In [62]:
# TF(t,d) = (Number of occurence of term t in document d)/(Total number of terms in the document d)
# Example =>
# d1 = people watch cricket.
# tf(people,d1)=1/3

In [63]:
# IDF(t) = log(Total number of document in the corpus)/(Number of documents with term t in them)
# here corpus means number of sentences
# Example =>
# d1 = people watch cricket.
# d2 = cricker was cricket.
# d3 = people write comment.
# d4 = cricket write comment.

# idf(cricket) = log(4/4)
# idf(people) = log(4/2)

In [64]:
# we can use this by applying feature extraction method in sklearn

In [65]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [67]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']
